/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.tsinghua.netbeans;

import cn.edu.tsinghua.util.JFrameUtil;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author liulei
 */
public class UseProfileUI extends javax.swing.JFrame {
    JToggleButton[] toggleButtons = null;
    /**
     * Creates new form NumberAdditionUI
     */
    public UseProfileUI() {
        super("OPERATIONAL PROFILE");
        initComponents();
        //设置界面在屏幕中居中显示
        JFrameUtil.setFrameLocationToMiddle(this);
        this.setResizable(false);
        toggleButtons = new JToggleButton[]{operateJTB,orderJTB,endJTB,possibilityJTB,packageJTB};
    }

    public UseProfileUI(String projectName) {
        super("使用剖面构造");
        initComponents();
        //设置界面在屏幕中居中显示
        JFrameUtil.setFrameLocationToMiddle(this);
        this.setResizable(false);
        toggleButtons = new JToggleButton[]{operateJTB,orderJTB,endJTB,possibilityJTB,packageJTB};
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        operateJTB = new javax.swing.JToggleButton();
        orderJTB = new javax.swing.JToggleButton();
        endJTB = new javax.swing.JToggleButton();
        possibilityJTB = new javax.swing.JToggleButton();
        packageJTB = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 600, 500));

        operateJTB.setText("操作");
        operateJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operateJTBActionPerformed(evt);
            }
        });
        getContentPane().add(operateJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 90, 40));

        orderJTB.setText("顺序转移");
        orderJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderJTBActionPerformed(evt);
            }
        });
        getContentPane().add(orderJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, 40));

        endJTB.setText("终止");
        endJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endJTBActionPerformed(evt);
            }
        });
        getContentPane().add(endJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 90, 40));

        possibilityJTB.setText("概率转移");
        possibilityJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                possibilityJTBActionPerformed(evt);
            }
        });
        getContentPane().add(possibilityJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 40));

        packageJTB.setText("包");
        packageJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageJTBActionPerformed(evt);
            }
        });
        getContentPane().add(packageJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 90, 40));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("请在下面的方框内构造系统的使用剖面：");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 470, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //点击其中一个toggleButton其他都置为非选择的
    private void toggleButtonAction(java.awt.event.ActionEvent evt){
        System.out.println("toggle button length:"+toggleButtons.length);
        for(JToggleButton toggleButton : toggleButtons){
            toggleButton.setSelected(false);
        }
        JToggleButton thisToggleButton = (JToggleButton) evt.getSource();
        thisToggleButton.setSelected(true);
    }
    
    private void operateJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operateJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_operateJTBActionPerformed

    private void orderJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_orderJTBActionPerformed

    private void endJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_endJTBActionPerformed

    private void possibilityJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_possibilityJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_possibilityJTBActionPerformed

    private void packageJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_packageJTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UseProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UseProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UseProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UseProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         //设置控件格式适应当前系统
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        } 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UseProfileUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JToggleButton endJTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton operateJTB;
    private javax.swing.JToggleButton orderJTB;
    private javax.swing.JToggleButton packageJTB;
    private javax.swing.JToggleButton possibilityJTB;
    // End of variables declaration//GEN-END:variables
}
