/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.tsinghua.netbeans;

import cn.edu.tsinghua.netbeans.model.PaintPanel;
import cn.edu.tsinghua.util.JFrameUtil;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.RectangularShape;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author liulei
 */
public class UseProfileUI extends javax.swing.JFrame {
    JToggleButton[] toggleButtons = null;
    
    //自定义画板JPanel
    PaintPanel paintPanel;
    /**
     * Creates new form NumberAdditionUI
     */
    public UseProfileUI() {
        super("OPERATIONAL PROFILE");
        initComponents();
        //设置界面在屏幕中居中显示
        JFrameUtil.setFrameLocationToMiddle(this);
        this.setResizable(false);
        paintPanel = (PaintPanel) jPanel2;
        toggleButtons = new JToggleButton[]{operateJTB,orderJTB,endJTB,possibilityJTB,packageJTB};
    }

    public UseProfileUI(String projectName) {
        super("使用剖面构造");
        initComponents();
        //设置界面在屏幕中居中显示
        JFrameUtil.setFrameLocationToMiddle(this);
        this.setResizable(false);
        paintPanel = (PaintPanel) jPanel2;
        toggleButtons = new JToggleButton[]{operateJTB,orderJTB,endJTB,possibilityJTB,packageJTB};
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new PaintPanel();
        operateJTB = new javax.swing.JToggleButton();
        orderJTB = new javax.swing.JToggleButton();
        endJTB = new javax.swing.JToggleButton();
        possibilityJTB = new javax.swing.JToggleButton();
        packageJTB = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 600, 500));

        operateJTB.setText("操作");
        operateJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operateJTBActionPerformed(evt);
            }
        });
        getContentPane().add(operateJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 90, 40));

        orderJTB.setText("顺序转移");
        orderJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderJTBActionPerformed(evt);
            }
        });
        getContentPane().add(orderJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, 40));

        endJTB.setText("终止");
        endJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endJTBActionPerformed(evt);
            }
        });
        getContentPane().add(endJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 90, 40));

        possibilityJTB.setText("概率转移");
        possibilityJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                possibilityJTBActionPerformed(evt);
            }
        });
        getContentPane().add(possibilityJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 40));

        packageJTB.setText("包");
        packageJTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageJTBActionPerformed(evt);
            }
        });
        getContentPane().add(packageJTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 90, 40));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("请在下面的方框内构造系统的使用剖面：");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 470, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //点击其中一个toggleButton其他都置为非选择的
    private void toggleButtonAction(java.awt.event.ActionEvent evt){
        System.out.println("toggle button length:"+toggleButtons.length);
        for(JToggleButton toggleButton : toggleButtons){
            toggleButton.setSelected(false);
        }
        JToggleButton thisToggleButton = (JToggleButton) evt.getSource();
        thisToggleButton.setSelected(true);
        
        Shape shape = null;
        if(thisToggleButton == operateJTB){
            shape = new Ellipse2D.Float();
        }
        paintPanel.shape = shape;
        
        System.out.println("The shape : "+ shape.toString());
    }
    
    private void operateJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operateJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_operateJTBActionPerformed

    private void orderJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_orderJTBActionPerformed

    private void endJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_endJTBActionPerformed

    private void possibilityJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_possibilityJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_possibilityJTBActionPerformed

    private void packageJTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageJTBActionPerformed
        toggleButtonAction(evt);
    }//GEN-LAST:event_packageJTBActionPerformed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        paintPanel.shapeList.add(paintPanel.shape);
        System.err.println("shape list size is " + paintPanel.shapeList.size());
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        paintPanel.start = evt.getPoint();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        paintPanel.end = evt.getPoint(); 
        ((RectangularShape) paintPanel.shape).setFrameFromDiagonal(paintPanel.start, paintPanel.end);
        repaint();
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UseProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UseProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UseProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UseProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         //设置控件格式适应当前系统
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        } 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UseProfileUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton endJTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton operateJTB;
    private javax.swing.JToggleButton orderJTB;
    private javax.swing.JToggleButton packageJTB;
    private javax.swing.JToggleButton possibilityJTB;
    // End of variables declaration//GEN-END:variables
}
